### ISSUE TITLE
Support for global autoprefixer config ?

### ISSUE THREAD

**Issue by oasisvali** [planttheidea/react-style-tag#11]
From the code, it appears that there is no way to pass in a autoprefixer config (such as `browsers`) for the component. I could see this being useful for our project where we support a very specific set of browsers (defined in our `browserslist`) and we would like to share that config for the autoprefixer with this component.

If this is something that makes sense to add to this project, I can get a PR going 😄

**Comment by planttheidea** [comment]
Yeah, go for it! Any and all PRs are welcome. :)

**Comment by oasisvali** [comment]
Cool! I am thinking of doing this as 2 separate PRs:

1) Accept the autoprefixer config as a `Style` config and pass it through to the autoprefixer, and then 
2) read the browserslist config directly if it exists (I'll look into the autoprefixer lib code to check how it does it on node).

I'll try and get the first one up today/tomorrow. Thanks for the lib!
