### ISSUE TITLE
Use caniuse-lite

### ISSUE THREAD

**Issue by Aubron** [planttheidea/react-style-tag#16]
In situations in which prefixing is used, using https://github.com/ben-eb/caniuse-lite instead of caniuse-db will decrease bundle bloat significantly.

**Comment by planttheidea** [comment]
Unfortunately this is not something I have direct control over, as it is a sub dependency of postcss. I have been meaning to update this library to use stylis instead of postcss, which should help with the bundle size but it's a complete rewrite.

**Comment by Aubron** [comment]
Fair enough, hadn't considered the intermediary dependency. As it stands I was just using it for dynamic addition of @font-face rules, so I rewrote to use custom code. A warning in the README at some point would be useful, I spent an unfortunate amount of time trying to shake out where the caniuse-db was being included at build time. Cheers!

**Comment by planttheidea** [comment]
@Aubron I had some time so I rewrote this component from scratch using `stylis` as aforementioned, and the size of the package has dropped considerably (~7.7KB minified + gzipped). I'll leave this open until that is complete, but hopefully things should be much more in line with expectations after the change.

**Comment by planttheidea** [comment]
@Aubron the rewrite is complete, I just published `2.0.0` which has a significantly smaller footprint. As such, I'm going to close this issue as it is no longer applicable (both the size concerns, and the caniuse-lite changes), but feel free to open up a new issue if you future bundle-size issues.
