### ISSUE TITLE
Warning: componentWillUpdate has been renamed

### ISSUE THREAD

**Issue by vercamach** [planttheidea/react-style-tag#30]
Hello,

When I render the component I get in my console a warning.

`Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Style`

Is that something I should be concerned about or will it be fixed?

Thank you

**Comment by planttheidea** [comment]
You should not be concerned. The method is still supported, it is just warning that the method is  scheduled for removal in a future React version.

I can update the library this weekend to use the UNSAFE prefix, which should remove the warning, but you can ignore this warning for now. I'll keep this issue open until this update occurs.

**Comment by planttheidea** [comment]
I have just published `2.0.3`, which should prevent this warning from appearing. If you have any more issues, let me know!
