### ISSUE TITLE
Warning: componentWillUpdate has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by FunctionDJ** [planttheidea/react-style-tag#38]
> Warning: componentWillUpdate has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * Rename componentWillUpdate to UNSAFE_componentWillUpdate to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: Style

![image](https://user-images.githubusercontent.com/34871211/127745429-114cbdc7-454e-41b4-8547-536103e71c27.png)

**Comment by planttheidea** [comment]
What version are you using? The latest version (`2.0.3`) should no longer have this issue.

**Comment by FunctionDJ** [comment]
> What version are you using? The latest version (`2.0.3`) should no longer have this issue.

2.0.3 😔. Encountered this while using it in a codesandbox project: https://codesandbox.io/s/sleepy-sunset-56zvh.
You should be able to just open it and see it as the only warning in the console.

**Comment by planttheidea** [comment]
Looks like my previous fix was naive, and did not support React 17. I have released `2.0.4` which should resolve this issue. Let me know if there are any further issues!

**Comment by FunctionDJ** [comment]
~~It's still there, just now being reported using `console.error()` 😅
https://codesandbox.io/s/sleepy-sunset-56zvh~~

Edit: Nevermind, the original issue is gone. This error reports the usage of `UNSAFE_` methods at all. Should i turn strict mode off?

**Comment by planttheidea** [comment]
Up to you, but despite the severity of the console notification it is just helpful for developers. This should not cause any issues functionality.
