### ISSUE TITLE
move `hasSourceMap` and `isMinified` to static?

### ISSUE THREAD

**Issue by nippur72** [planttheidea/react-style-tag#4]
I'm not really sure of this, but isn't it better to have `hasSourceMap` and `isMinified` as static properties so to not have to explicit them for every instance? E.g.

``` js
// before loading any other styles
import Style from 'react-style-tag';
const IS_PRODUCTION = process.env.NODE_ENV === 'production';
Style.hasSourceMap = !IS_PRODUCTION ;
Style.isMinified = IS_PRODUCTION;
```

**Comment by planttheidea** [comment]
I like the idea, but not setting statics directly like that ... feels wrong mutating the object directly. I'm going a static `setGlobalOptions(options)` direction where `options` is an object of properties matching the props values. This way if theoretically they set global values but did want to override it on the instance level they could.

I'll be releasing 1.2.0 shortly with this enhancement.

**Comment by planttheidea** [comment]
1.2.0 has been released with the method described, and README has been updated with the documentation of use! Closing. :)
