### ISSUE TITLE
Typescript types?

### ISSUE THREAD

**Issue by ryanscottaudio** [planttheidea/react-style-tag#49]
It would be helpful to have a `.d.ts` file or a `@types/react-style-tag` npm module.

**Comment by planttheidea** [comment]
My time is a bit constrained right now, so I have not been able to tackle this, and probably won't for some time. PRs are always welcome, though!

**Comment by planttheidea** [comment]
This will be tackled in [V3](https://github.com/planttheidea/react-style-tag/pull/54), which should be out shortly.

**Comment by planttheidea** [comment]
This should be fixed with `3.0.0`, which has just been released. If you have any more issues, let me know!
