### ISSUE TITLE
Support for react@18.x

### ISSUE THREAD

**Issue by creatorrr** [planttheidea/react-style-tag#53]
Is there any particular reason `react@18.x` is not supported? If there aren't any major standing issues, can you please add support? Happy to raise a PR.

**Comment by planttheidea** [comment]
Nope, just naive versioning.

I'll be tackling this in [V3](https://github.com/planttheidea/react-style-tag/pull/54), which should be in shortly.

**Comment by planttheidea** [comment]
This should be fixed with `3.0.0`, which has just been released. If you have any more issues, let me know!

**Comment by creatorrr** [comment]
Thanks @planttheidea !
